article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),

    
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/',views.profileUser,name="profile"),
    path('addprofile/',views.addProfile,name="addprofile"),
    path('editprofile/',views.editProfile,name="editprofile"),

    
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">YB Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</span></a>
        </li>
        
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</span></a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:profile' %}">Profil</span></a>
            </li>
        {% else %}
          <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</span></a>
        </li>
        
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</span></a>
        </li>
        
        
        
        
        
      </ul>
      
    </div>
  </nav>

templates/includes/posttemplate.html
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on January 1, 2022 by Start Bootstrap</div>
                <!-- Post categories-->
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
            </header>
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
            </section>
        </article>



        <ul class="media-list">
            <li class="media">
                <a href="#" class="pull-left">
                    <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle">
                </a>
                <div class="media-body">
                    <span class="text-muted pull-right">
                        <small class="text-muted">30 min ago</small>
                    </span>
                    <strong class="text-success">@MartinoMont</strong>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Lorem ipsum dolor sit amet, <a href="#">#consecteturadipiscing </a>.
                    </p>
                </div>
            </li>
            
        </ul>
             