article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),

    
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author=models.ForeignKey('auth.user', on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content=RichTextField(verbose_name='İçerik')
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image=models.FileField(blank=True, null= True, verbose_name='Makaleye Fotoğraf Ekleyin')
    def __str__(self):
        return self.title   #Makale Başlığını article object yerine yazıyor.
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name='Makale',related_name='comments')
    comment_author=models.CharField(max_length=50,verbose_name='isim')
    comment_content=models.CharField(max_length=200,verbose_name='Yorum')
    comment_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
     class Meta:
        model = Article
        fields = ['title','content','article_image']

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Article,Comment

# Create your views here.
def articles(request):
    keyword=request.GET.get('keyword')
    if keyword:
        articles=Article.objects.filter(title__contains=keyword)
        return render(request,'articles.html',{'articles':articles})
    articles=Article.objects.all()
    
    return render(request,'articles.html',{'articles':articles})
def index(request):
    
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")
@login_required(login_url='/user/login/')
def dashboard(request):
    articles=Article.objects.filter(author = request.user)

    context = {
        'articles':articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url='/user/login/')
def addArticle(request):
    form=ArticleForm(request.POST or None, request.FILES or None)

    context={
        'form':form
    }
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,'Makale başarı ile kaydedilmiştir.')
        return redirect('index')
    return render(request,"addarticle.html",context)
@login_required(login_url='/user/login/')
def detail(request,id):
    #article=Article.objects.filter(id = id)[0]
    article=get_object_or_404(Article,id=id)
    comments=article.comments.all()
    return render(request,'detail.html',{'article':article,'comments':comments})
@login_required(login_url='/user/login/')
def updateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form=ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,'Makale başarı ile güncellenmiştir.')
        return redirect('index')

    return render(request,'update.html',{'form':form})
@login_required(login_url='/user/login/')
def deleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,'Makale başarı ile silinmiştir.')
    return redirect('article:dashboard')

def addComment(request,id):
    article=get_object_or_404(Article,id=id)
    
    if request.method=='POST':
        comment_author=request.POST.get('comment_author')
        comment_content=request.POST.get('comment_content')

        newComment=Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article=article
        newComment.save()
    return redirect(reverse('article:detail',kwargs={'id':id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}

<h3>Hakkımızda</h3>
<hr>
<p>
    Herkese merhabalar. Ben Matematik Öğretmeni Mert YÜCE. Hacettepe Üniversitesi Ortaöğretim Matematik Öğretmenliği bölümünden 2014 yılında mezun olduktan sonra aynı yıl Nevşehir'in Kozaklı ilçesine atamam gerçekleşti. 2014 - 2017 yılları arasında Hacettepe Üniversitesi Matematik Eğitimi bölümünde yükseklisans programını tamamladım. 2017 yılında İstanbul'a il dışı tayin hakkımı kullanarak geldim. Bu süreçte zaman zaman programlama alanında çalışma yapmak istesemde düzenli bir çalışma programı uygulayamadım. Ancak son bir kaç aydır bunu gerçekleştirmeye çalışıyorum ve belli bir yol katedeceğimi düşünüyorum. Sizinde bu alanda çalışma ve bilgilerinizi paylaşma gibi bir düşünceniz varsa sayfamda bu tür paylaşımlara yer vermenizden mutluluk duyarım.
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h3> Makale Oluştur </h3>
        <hr>  
        <form method="POST" class="bootstrap4" enctype="multipart/form-data">
            {% csrf_token %}
        {{form | crispy}}
        {{form.media}}
        
        <br>
        <button type="submit" class="btn btn-danger">Makale Ekle</button>
    </div>
</div>


</form>

{% endblock body %}

templates/addprofile.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h3> Profil Oluştur </h3>
        <hr>  
        <form method="POST" class="bootstrap4" enctype="multipart/form-data">
            {% csrf_token %}
        {{form | crispy}}
        {{form.media}}
        
        <br>
        <button type="submit" class="btn btn-danger">Profil Oluştur</button>
    </div>
</div>


</form>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="row" >
    <div class="col-md-9 offset-md-2">
        <div class="col-lg-11">    
<h2>  Makaleler</h2>
<hr>

<form class="form-inline my-2 my-lg-0">
    {% csrf_token %}
    <input class="form-control mr-sm-2" type="search" placeholder="Ara..." aria-label="Search" name="keyword" >
    <button class="btn btn-danger" type="submit">Ara</button>
</form>
    <br>
</div>
</div>
</div>

    


{% if articles %}
{% for article in articles %}
<div class="row">
    <div class="col-md-9 offset-md-2">
    <div class="col-lg-11">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-2">{{article.title}}</h2></a>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">by {{article.author}}</div>
                <hr>
                <p>{{article.created_date}}</p>
                <hr>
                
                
            </header>
            {% if article.article_image %}
            <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" width='300'src="{{article.article_image.url}}" alt="..." /></figure></a>
            
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-6 mb-6">{{article.content | safe | truncatewords:51}}</p>
                
                <a style="float : right;" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamını Oku</a>
                <hr>     
                
            </section>
        </article>
        
    </div>
</div>
</div>
{% endfor %}
{% else %}

    <div class="row" >
        <div class="col-md-9 offset-md-2">
            <div class="col-lg-8">        
                <div class="alert alert-danger">
                Makale bulunamadı.
    </div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz <small>{{request.user.username}}</small>
</p>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col" >Güncelle</th>
        <th scope="col" >Sil</th>
      </tr>
    </thead>
    {% for article in articles %}
    <tbody>
      <tr>
        <th scope="row">{{article.id}}</th>
        <td>
        <a href="{% url 'article:detail' article.id %}">{{article.title}}</a>
        
        </td>
        <td>{{article.author}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a></td>
        <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>

      </tr>
    </tbody>
    {% endfor %}
      
  </table>

{% else %}
<div class="alert alert-danger">
Henüz bir makaleniz bulunmamaktadır.
</div>
{% endif %}

<a class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
<hr>
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h2 class="fw-bolder mb-2">{{article.title}}</h2>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">by {{article.author}}</div>
                <hr>
                <p>{{article.created_date}}</p>
                <hr>
                
                
            </header>
            {% if article.article_image %}
            <figure class="mb-4"><img class="img-fluid rounded" width='300' src="{{article.article_image.url}}" alt="..." /></figure>
            
            {% endif %}
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">{{article.content | safe}}</p>
                
                
            </section>
        </article>
        <div class="container">
            <div class="row bootstrap snippets bootdeys">
                <div class="col-md-11 col-sm-12">
                    <div class="comment-wrapper">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                            <h5>Yorumlar</h5>
                            <hr>
                                {% if comments %}
                                {% for comment in comments %}
                                <ul class="media-list">
                                    <li class="media">
                                        <a href="#" class="pull-left">
                                            <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle" width="50">
                                        </a>
                                        <div class="media-body">
                                            <strong class="text-success">{{comment.comment_author}}</strong>
                                            <br>
                                            <span class="text-muted pull-right">
                                                <small class="text-muted">{{comment.comment_date}}</small>
                                            </span>
                                            
                                            <p>
                                                {{comment.comment_content}}
                                            </p>
                                        </div>
                                    </li>
                                    
                                </ul>
                                
                                
                                {% endfor %}
                                
                                {% else %}
                                <div class="alert alert-danger">
                                    Bu makaleye herhangi bir yorum yazılmamış,ilk yorum yapan siz olun!
                                </div>
                                {% endif %}
                                
                                <h6>Yorum Ekle:</h6>
                                <hr>
                            </div>
                            <form method='post' action= "{% url 'article:comment' article.id %}" >
                                {% csrf_token %}
                            <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input name='comment_author' type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi yazınız...">
                            </div>
                    
                            
                            <div class="form-group">
                            <label for="formGroupExampleInput">Yorum</label>
                                <textarea name='comment_content' class="form-control" placeholder="Yorum yazınız..." rows="3"></textarea>
                                <br>
                                <button type="submit" class="btn btn-info pull-right">Ekle</button>
                                <div class="clearfix"></div>
                                <hr>
                            </form>    
                              
                                
                            </div>
                        </div>
                    </div>
            
                </div>
            </div>
            </div>
    </div>
</div>
{% endblock body %}

templates/editprofile.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h3> Profil Düzenleme </h3>
        <hr> 
        <form method="POST" class="bootstrap4" enctype="multipart/form-data">
            {% csrf_token %}
        {{form | crispy}}
        {{form.media}}
        
        <br>
        <button type="submit" class="btn btn-danger">Profil Güncelle</button>
    </div>
</div>


</form>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}

<div class="jumbotron text-center">
    <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilir ve insanlara yardımcı olabilirsiniz.</p>

</div>
<p>
    {% if request.user.is_authenticated %}
        Giriş Yapılmış {{request.user.username}}
    
    {% else %}
        Giriş Yapılmamış
    {% endif %}
</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Ybblog</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    <div style="margin-top: 100px; margin-bottom: 100px;" class="container">
        {% if messages %}
        
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
        
            {% endfor %}
        {% endif %}
    {% block body %}
    
    {% endblock body %}
        

    </div>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        {% if 'next' in request.GET %}
        <p style='color:rgb(255, 0, 0); font-size:110%;'>Sayfayı görüntülemek için giriş yapınız</p>
    
        {% endif %}
        <h3> Giriş Yap </h3>
        <hr>
        
        <form method="POST" class="bootstrap4">
            {% csrf_token %}
        {{form | crispy}}
        <br>
        <button type="submit" class="btn btn-danger">Giriş Yap</button>
    </div>
</div>


</form>
{% endblock body %}

templates/profile.html
{% extends "layout.html" %}

{% block body %}
<div class="row" >
    <div class="col-md-11 offset-md-2" style="left: 15px;">

<hr>
</div>
</div>

<div>
        
            <figure class="mb-4"><img class="img-fluid rounded" width='175'src="{{profile.user_image.url}}" alt="..." /></figure>
            
            <br>
            <h5 class="fw-bolder mb-2">İsim: {{profile.name}}</h5>
                
            <h5 class="fw-bolder mb-2">Soyisim: {{profile.surname}}</h5>
            <h5 class="fw-bolder mb-2">Email: {{profile.email}}</h5>
            <hr>
            <a href="/user/editprofile" class="btn btn-danger">Profil Düzenle</a>
            
                
            
            
        
    
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h3> Kayıt Ol </h3>
        <hr>  
        <form method="POST" class="bootstrap4">
            {% csrf_token %}
        {{form | crispy}}
        <br>
        <button type="submit" class="btn btn-danger">Kayıt Ol</button>
    </div>
</div>


</form>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h3> Makale Güncelle </h3>
        <hr>  
        <form method="POST" class="bootstrap4" enctype="multipart/form-data">
            {% csrf_token %}
        {{form | crispy}}
        {{form.media}}
        
        <br>
        <button type="submit" class="btn btn-danger">Makale Güncelle</button>
    </div>
</div>


</form>

{% endblock body %}